#!/usr/bin/env lua

-- check linux cpu by "top -b -n 1" 
-- author: ery.lee@gmail.com from monit.cn

require("plugin")

function check() 
  output = os.cmd("top -b -n 1")
  names = {"user","system","nice","idle","iowait"} 
  values = {string.match(output, "%s+([0-9]+.[0-9]+)%%us,%s+([0-9]+.[0-9]+)%%sy,%s+([0-9]+.[0-9]+)%%ni,%s+([0-9]+.[0-9]+)%%id,%s+([0-9]+.[0-9]+)%%wa")}
  if #values ~= 5 then
    print "UNKNOWN - unknown command output\n"
    return
  end
  metrics = table.zip(names, values)
  usage = 100 - tonumber(metrics["idle"])
  print(string.format("OK - usage = %.2f%%\n", usage))
  print("metric:usage: "..usage.."%")
  for k,v in pairs(metrics) do
    print(string.format("metric:%s: %s%%", k, v))
  end
end

function usage()
  print("Usage: check_cpu.lua")
end

ok, err = pcall(check)
if not ok then
  print("UNKNOWN - plugin internal error\n")
  print(err)
end
