#!/usr/bin/env lua

-- check mysql traffic by "show global status like 'Bytes_%'"
-- author: ery.lee@gmail.com from monit.cn

require("plugin")

-- do check
function check(opts) 
  require("luasql.mysql")
  env = assert (luasql.mysql())
  con = assert (env:connect("mysql", opts["username"], opts["password"], opts["host"], tonumber(opts["port"])))
  -- retrieve status
  cur = assert (con:execute"show global status where Variable_name in('Bytes_received', 'Bytes_sent')")
  row = cur:fetch ({}, "a")
  metrics = {}
  while row do
    metric = string.sub(row.Variable_name, string.len('Bytes_') + 1)
    metrics[metric] = row.Value
    row = cur:fetch (row, "a")
  end
  -- print result
  print(string.format("OK - sent = %s, received = %s", metrics["sent"], metrics["received"]))
  print("count-metrics: sent,received\n") 
  for k,v in pairs(metrics) do
    print(string.format("metric:%s: %s", k, v))
  end
  -- close everything
  cur:close()
  con:close()
  env:close()
end

-- usage
function usage() 
  print("usage: check_mysql_bytes --host=Host --username=User --password=Password --port=Port")
end

-- parse arguments
opts = getopt(arg, {"host", "password", "username", "port"})
if not opts["port"] then opts["port"] = "3306" end
for i, o in ipairs({"host", "password", "username"}) do
  if not opts[o] then
    print(string.format("UNKNOWN - miss argument = '%s'\n", o))
    usage()
    return
  end
end

status, err = pcall(check, opts) 
if not status then
  print("UNKNOWN - plugin internal error\n")
  print(err)
end

