#!/usr/bin/env lua

-- check mysql commands by "show global status like 'Bytes_%'"
-- author: ery.lee@gmail.com from monit.cn

require("plugin")

-- do check
function check(opts) 
  require("luasql.mysql")
  env = assert (luasql.mysql())
  con = assert (env:connect("mysql", opts["username"], opts["password"], opts["host"], tonumber(opts["port"])))
  -- retrieve status
  cur = assert (con:execute"show global status where Variable_name in('Questions','Com_select','Com_update','Com_insert','Com_delete','Com_commit','Com_rollback');")
  row = cur:fetch ({}, "a")
  metrics = {}
  while row do
    name = string.gsub(string.lower(row.Variable_name), "com_", "")
    metrics[name] = row.Value
    row = cur:fetch (row, "a")
  end
  metrics["transactions"] = tonumber(metrics["commit"]) + tonumber(metrics["rollback"])
  -- print result
  print(string.format("OK - questions = %s, transactions = %s", metrics['questions'], metrics['transactions']))
  print("count-metrics: questions,transactions,select,update,insert,delete,commit,rollback\n") 
  for k,v in pairs(metrics) do
    print(string.format("metric:%s: %s", k, v))
  end
  -- close everything
  cur:close()
  con:close()
  env:close()
end

-- usage
function usage() 
  print("usage: check_mysql_cmd --host=Host --username=User --password=Password --port=Port")
end

-- parse arguments
opts = getopt(arg, {"host", "password", "username", "port"})
if not opts["port"] then opts["port"] = "3306" end
for i, o in ipairs({"host", "password", "username"}) do
  if not opts[o] then
    print(string.format("UNKNOWN - miss argument = '%s'\n", o))
    usage()
    return
  end
end

status, err = pcall(check, opts) 
if not status then
  print("UNKNOWN - plugin internal error\n")
  print(err)
end

