#!/usr/bin/env python

"""
Check swap by free -o
"""
import os, re, sys, getopt

def run(Args):
    pipe = os.popen("free -o")
    output = pipe.read()
    pipe.close
    match = re.search(r'Swap:\s*(\d+)\s+(\d+)\s+(\d+)', output) 
    if match == None:
        print "UNKNOWN - cannot parse", output
        return
    total = int(match.group(1)) * 1024
    used = int(match.group(2))  * 1024
    free = int(match.group(3)) * 1024
    usage = int(used / total)
    data = {'total': total, 'used': used, 'free': free, 'usage': str(usage) + '%'}
    summary = "swap usage = " + str(usage) + "%"
    metrics = ", ".join([name + "=" + str(val) for name, val in data.iteritems()])
    print "OK -", summary, "|", metrics

def usage():
    print "Usage: check_swap_free -h"

if __name__ == "__main__":
    try:
        opts, args = getopt.getopt(sys.argv[1:], "h", ["help"])
    except getopt.GetoptError, err:
    # print help information and exit:
        print "UNKNOWN -", str(err)
        sys.exit(2)
    for o, a in opts:
        if o in ("-h", "--help"):
            usage(),
            sys.exit(0)
        else:
            print "UNKNOWN - error argument:" + o
            usage()
            sys.exit(2)
    try:
        run({})
    except:
        print "UNKNOWN - access status page error:", sys.exc_info()[0]
        sys.exit(2)
