#!/usr/bin/env lua

-- check_disk_df

dofile("plugin.lua")

function check(opts)
  output = runcmd("df "..opts["path"])
  lines = split(output, "[\r\n]+")
  for i,line in pairs(lines) do
    pat = "^([^%s]+)%s+(%d+)%s+(%d+)%s+(%d+)%s+(%d+)%%" 
    _,_,fs,total,used,avail,usage = string.find(line, pat)
    if usage then
      print(string.format("OK - usage = %s%%, total = %.2fG\r\n", usage, total/(1000*1000)))
      print("metric: usage="..usage.."%")
      print("metric: total="..total.."KB")
      print("metric: used="..used.."KB")
      print("metric: avail="..avail.."KB")
      return
    end
  end
  print("UNKNOWN - "..lines[1].."\r\n")
end

function usage() 
  print("check_disk_df --path=Path")
end

-- parse arguments
opts = getopt(arg, {"path"})
if not opts["path"] then
  print("UNKNOWN - miss argument = 'path'\r\n")
  usage()
  return
end

ok, err = pcall(check, opts)
if not ok then
  print("UNKNOWN - plugin internal error\r\n")
  print(err)
end
