#!/usr/bin/env lua

-- check_disk_df

dofile("plugin.lua")

function check() 
  output = runcmd("top -b -n 1")
  lines = split(output, "[\r\n]+")
  if table.getn(lines) < 3 then
    print "UNKNOWN - unknown command output\r\n"
    return
  end
  cpuinfo = lines[3]
  _,_,user,system,nice,idle,iowait = string.find(cpuinfo, "%s+([0-9]+.[0-9]+)%%us,%s+([0-9]+.[0-9]+)%%sy,%s+([0-9]+.[0-9]+)%%ni,%s+([0-9]+.[0-9]+)%%id,%s+([0-9]+.[0-9]+)%%wa")
  usage = 100 - tonumber(idle)
  print("OK - usage = "..usage.."%\r\n")
  for k,v in pairs({usage=usage,user=user,system=system,nice=nice,idle=idle,iowait=iowait}) do
    print(string.format("metric: %s=%s%%", k, v))
  end
end

function usage()
  print("usage: check_cpu_top")
end

ok, err = pcall(check)
if not ok then
  print("UNKNOWN - plugin internal error\r\n")
  print(err)
end
