#!/usr/bin/env lua

-- check mysql connections 
-- author: ery.lee@gmail.com from monit.cn

require("plugin")

-- do check
function check(opts) 
  require "luasql.mysql"
  env = assert (luasql.mysql())
  con = assert (env:connect("mysql", opts["username"], opts["password"], opts["host"], tonumber(opts["port"])))
  -- retrieve status
  sql_variables = [[show global variables where Variable_name in 
                    ('table_open_cache')]]
  cur = assert (con:execute(sql_variables))
  variables = {}
  row = cur:fetch ({}, "a")
  while row do
    variables[row.Variable_name] = row.Value
    row = cur:fetch (row, "a")
  end
  sql_status = [[show global status where Variable_name in 
                 ('Open_tables', 'Opened_tables')]]
  cur = assert (con:execute(sql_status))
  metrics = {}
  row = cur:fetch ({}, "a")
  while row do
    metrics[string.lower(row.Variable_name)] = row.Value
    row = cur:fetch(row, "a")
  end
  metrics["opened_tables_rate"] = 0
  if metrics["opened_tables"] ~= "0" then
    metrics["opened_tables_rate"] = tonumber(metrics["open_tables"])*100/tonumber(metrics["opened_tables"])
  end
  metrics["open_table_cache_rate"] = 0
  if metrics["table_open_cache"] ~= "0" then
    metrics["open_table_cache_rate"] = tonumber(metrics["open_tables"])*100/tonumber(variables["table_open_cache"])
  end
  print(string.format("OK - table open cache = %s, open tables = %s", variables["table_open_cache"], metrics["open_tables"]))
  print("count-metrics: opened_tables\n") 
  for k, v in pairs(variables) do
    print(string.format("entry:variable:%s: %s", k, v))
  end
  for k,v in pairs(metrics) do
    print(string.format("metric:%s: %s", k, v))
  end
  -- close everything
  cur:close()
  con:close()
  env:close()
end

-- usage
function usage() 
  print("Usage: check_mysql_opentab --host=Host --username=User --password=Password --port=Port")
end

-- parse arguments
opts = getopt(arg, {"host", "password", "username", "port"})
if not opts["port"] then opts["port"] = "3306" end
for i, o in ipairs({"host", "password", "username"}) do
  if not opts[o] then
    print(string.format("UNKNOWN - miss argument = '%s'\n", o))
    usage()
    return
  end
end

status, err = pcall(check, opts) 
if not status then
  print("UNKNOWN - plugin internal error\n")
  print(err)
end

