#!/usr/bin/env python

"""
discover disks
"""
import os, re, sys, getopt

def run(args):
  pipe = os.popen("df")
  output = pipe.read()
  pipe.close
  lines = output.split("\n")
  lines.pop(0)
  disks = []
  for line in lines:
    match = re.search(r'\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)%\s+([\/\w]+)$', line) 
    if match != None:
      total = int(match.group(1)) * 1024
      used = int(match.group(2)) * 1024
      avail = int(match.group(3)) * 1024
      usage = int(match.group(4))
      mount = match.group(5)
      if not ((total == 0) or (used == 0) or (avail == 0)):
        disks.append((mount, usage, total, used, avail))
  summary = "disks discovered"
  services = " | ".join([new(disk) for disk in disks])
  print "OK -", summary, "|", services

def new(disk):
  name = "Disk - " + disk[0]
  command = "check_disk_df"
  params = "path=" + disk[0]
  return "name=%s,command=%s,params=%s" % (name, command, params)

def usage():
    print "usage: disco_disk_df"

if __name__ == "__main__":
    try:
        opts, args = getopt.getopt(sys.argv[1:], "h", ["help"])
    except getopt.GetoptError, err:
    # print help information and exit:
        print "UNKNOWN -", str(err)
        sys.exit(2)
    try:
      run({})
    except:
      print "UNKNOWN -", sys.exc_info()[0]
      sys.exit(2)

