#!/usr/bin/env lua

-- scan_nmap
-- author: ery.lee@gmail.com from monit.cn

require("plugin")

-- do scan
function scan(opts) 
  local output = os.cmd("nmap -F -sU -sT --host-timeout 20000 "..opts["host"])
  if string.find(output, "root privileges") then 
    print("UNKNOWN - "..string.split(output, "\n")[1])
    return
  end
  local patten = "^(%d+)/([tcudp]+)%s+([%w|]+)%s+([%w%-]+)$"
  local lines = string.split(output, "[\r\n]+")
  local entries = {}
  for _,line in pairs(lines) do
    port,proto,state,service = string.match(line, patten)
    if service then
      table.insert(entries, {port = port, proto = proto, state = state, service = service})
    end
  end
  local tcps = table.filter(entries, function(entry) return (entry.proto == "tcp") end)
  local udps = table.filter(entries, function(entry) return (entry.proto == "udp") end)

  local tcp_ports = table.map(tcps, function(tcp) return tcp.port end)  
  local udp_ports = table.map(udps, function(udp) return udp.port end)

  print("OK - tcp ports = "..string.join(tcp_ports, "|")..", udp ports = "..string.join(udp_ports, "|").."\r\n")
  for _,entry in pairs(entries) do
    print(string.format("entry:%s:%s: port=%s,state=%s,service=%s", 
        entry.proto, entry.port, entry.port, entry.state, entry.service))
  end
end

-- usage
function usage() 
  print("Usage: scan_nmap --host=Host")
end

-- parse arguments
opts = getopt(arg, {"host"})
if not opts["host"] then
  print("UNKNOWN - miss argument = 'host'\r\n")
  usage()
  return
end

ok, err = pcall(scan, opts)
if not ok then
  print("UNKNOWN - plugin internal error\r\n")
  print(err)
end
