#!/usr/bin/env python

"""
scan by 'nmap' command.
"""

import os, re, sys, getopt

def run(args):
  host = args['host']
  pipe = os.popen('nmap -F -sU -sT --host-timeout 20000 ' + host)
  output = pipe.read()
  pipe.close
  lines = output.split("\n")
  ports = []
  for line in lines:
    if len(line) < 10:
      continue
    match = re.search(r'^(\d+/[udtcp]+)\s', line)
    if match != None:
      ports.append(line)  
  print "OK - scan ports successfully.", "\nPort\tState\tService\n", "\n".join(ports) 

def usage():
    print "Usage: check_ping --host=host"

if __name__ == "__main__":
  try:
    opts, args = getopt.getopt(sys.argv[1:], "h", ["help", "host="])
  except getopt.GetoptError, err:
  # print help information and exit:
    print "UNKNOWN -", str(err)
    sys.exit(2)
  cmd_args = {}
  for o, a in opts:
    if o in ("-h", "--help"):
      usage(),
      sys.exit(0)
    elif o in ("--host"):
      cmd_args['host'] = a
    else:
      print "UNKNOWN - error argument:" + o
      usage()
      sys.exit(2)
  if not ('host' in cmd_args):
    print "UNKNOWN - invalid arguments!"
    usage()
    sys.exit(2)
  try:
    run(cmd_args)
  except:
    print "UNKNOWN -", sys.exc_info()[0]
    sys.exit(2)

